### PR TITLE
Merge today's robot testing changes in main

### PR DESCRIPTION
**Pull request by theVerySharpFlat**

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
Please do not merge. I need to alter the controlType in SparkMaxVelocityController based on whether or not we are using smartMotion

**Comment by abheekda1** [comment]
@theVerySharpFlat you can always mark it as a draft if you want the PR to be here but unmergeable :)

**Comment by abheekda1** [comment]
@notSam25 please work on your commit messages 😆

**Comment by theVerySharpFlat** [comment]
I wish it would hurry up and do the checks. I really need this code.

**Comment by theVerySharpFlat** [comment]
Ok, I'm kinda going under @gcjurgiel 's nose, but I need the code.

**Pull request merged**
