### PR TITLE
Add clang-format check workflow for lib

### PR DESCRIPTION
**Pull request by abheekda1**
#17

### CODE REVIEW

**Comment by abheekda1** [comment]
Ok wait I have to figure out how to properly allow errors for `clang-format` first before merging but I'm not making this a draft because I want the workflows to check.

**Comment by theVerySharpFlat** [comment]
[motto.md](https://github.com/rambunction4330/RobotCode2022/blob/main/motto.md)

**Comment by abheekda1** [comment]
@theVerySharpFlat it builds ya moron, it just doesn't follow the guidelines.

**Comment by abheekda1** [comment]
That's literally the whole point of the PR.

**Comment by theVerySharpFlat** [comment]
> That's literally the whole point of the PR.

lmfao sorry

"@theVerySharpFlat it builds ya moron" - @ADawesomeguy 2022

**Comment by abheekda1** [comment]
XD

**Pull request closed without merging**
