### PR TITLE
Fiux the flywheel to use the proper units

### PR DESCRIPTION
**Pull request by gjurgiel**
I swapped the flywheel of the shooter over to meters per second as opposed to radians per second since we will only need to use the linear velocity unless you see reason to leave it as radians.

### CODE REVIEW

**Comment by abheekda1** [comment]
What’s the flywheel?

**Comment by gjurgiel** [comment]
It's the wheel that spins really fast to shoot the ball.

**Comment by theVerySharpFlat** [comment]
You deleted a bunch of my code 🎻🎻🎻🤧😭🎻🎻🎻

🪦🪦🪦🪦🪦🪦🪦

RIP angular velocity

**Comment by abheekda1** [comment]
George please spell fix for me

**Comment by gjurgiel** [comment]
ghoquec (and even worse, this is phonetically correct)

**Pull request merged**
