### PR TITLE
Create motorID.md

### PR DESCRIPTION
**Pull request by theVerySharpFlat**
Transcribed from a sheet of loose leaf.

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
TODO: add motorcontroller type

**Comment by theVerySharpFlat** [comment]
done

**Review by gjurgiel — CHANGES_REQUESTED** [review]
Storage is a Talon. The Flywheel is a SparkMax. It might also be worth noting that the spinner is a brushed motor.

**Comment by theVerySharpFlat** [comment]
> Storage is a Talon. The Flywheel is a SparkMax. It might also be worth noting that the spinner is a brushed motor.

fixed in [7658e78](https://github.com/rambunction4330/RobotCode2022/pull/104/commits/7658e7809c0ae511095c9c22e72f5753e3117a50) and [567576b](https://github.com/rambunction4330/RobotCode2022/pull/104/commits/567576b2630949247d74626c3023062e8c678a94)

**Review by gjurgiel — APPROVED** [review]

**Pull request merged**
