### PR TITLE
Doxygen Implementation

### PR DESCRIPTION
**Pull request by abheekda1**
Dunno why the other PR died but:

<hr>

Use this pull request to add documentation, once everything's finished the merge should hopefully go smoothly. Every once in a while we should make sure to merge main into here. 

To use:
- Commit to `doxygen` branch
- Push

#### TODO:
- [x] FeedForward
- [x] HolonomicDrive
- [x] HolonomicDriveOdometry
- [x] HolonomicTrajectoryCommand
- [x] MecanumDrive
- [x] MecanumEncoderOdometry
- [x] PositionController
- [x] SparkMaxPositionController
- [x] SparkMaxVelocityController
- [ ] TalonFXVelocityController
- [ ] TalonSRXVelocityController
- [x] VelocityController

- [x] Panskace

For the first commit I've just gone ahead and added an icon.

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
I will document VelocityController and PositionController, but I'm leaving Feedforward to @gcjurgiel

**Comment by abheekda1** [comment]
@gcjurgiel make sure to check off whatever you did in the original comment.

**Comment by gjurgiel** [comment]
I did!

**Comment by theVerySharpFlat** [comment]
### 🎉🎉🎉 VelocityController is documented! 🎉🎉🎉

Do you know what this means? We've documented all of the classes anybody feels any responsibility to document!

Should we merge?

**Review by theVerySharpFlat — APPROVED** [review]
Can we puh-leez merge?

**Comment by abheekda1** [comment]
Think we're done for now, nice job everyone!

**Pull request merged**
