### PR TITLE
Better Logging

### PR DESCRIPTION
**Pull request by theVerySharpFlat**
this should make printing things out a heck of a lot easier as it uses templates and overloading to make it easy to print things. I think I should look into whether or not the units:: library has a to_string function.

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
it would be really nice if we could test this code.

**Review by abheekda1 — COMMENTED** [review]
I don't know how to programming but it looks good to me.

**Comment by gjurgiel** [comment]
Yes! thank you, we need this! you may be able to test this through the simulation tools first provides.

**Review by gjurgiel — COMMENTED** [review]
You might want to make the OutStream object static since it will always be the same one. (C++ does this through making al functions and properties static... I'm pretty sure). It additionally might be helpful to add functioned for common container types like Pose2d.

**Comment by gjurgiel** [comment]
You might also be able to get way without defining a new stream type, and just defining new overload operators for different types to print?

**Comment by gjurgiel** [comment]
Would this work?
```
template<typename T>
wpi::raw_ostream& operator<<(wpi::raw_ostream& os, T& val) {
  os << std::to_string(val);
}
```

**Comment by theVerySharpFlat** [comment]
I've seen something like that defined with std::cout. i'll look into that.

**Comment by theVerySharpFlat** [comment]
Ok, so operators cannot be static, meaning we have to use an object. But I do think we can overload the << operator for wpi::raw_ostream or whatever its called.

**Comment by gjurgiel** [comment]
That's how I have always done it for std::cout, and based on a bit of testing it compiles for wpi::raw_ostream too. Although the code I commented above is incorrect. It seems like the `val` argument can't be reference. This is closer to what it should be:
```
template<typename T>
wpi::raw_ostream& operator<<(wpi::raw_ostream& os, T val) {
  os << std::to_string(val);
  return os;
}
```
 (For reference, I've been going off of [this](https://docs.microsoft.com/en-us/cpp/standard-library/overloading-the-output-operator-for-your-own-classes?view=msvc-170)).

**Comment by theVerySharpFlat** [comment]
> It seems like the `val` argument can't be reference

why not?

**Comment by gjurgiel** [comment]
You can! I just had a typo when I tested it.

**Comment by gjurgiel** [comment]
It does get upset if the reference isn't constant though.

**Comment by theVerySharpFlat** [comment]
> It does get upset if the reference isn't constant though.

That's stupid. We should be able to modify the user's data without them knowing.

**Comment by theVerySharpFlat** [comment]
@gcjurgiel the reason we weren't seeing logs in some cases was because the wpi::raw_ostream class only flushes when the buffer is full. So, we need to flush with [wpi::raw_ostream::flush()](https://first.wpi.edu/wpilib/allwpilib/docs/release/cpp/classwpi_1_1raw__ostream.html#a209f3bcca8657748af3db4bab3ca6f53)

**Comment by theVerySharpFlat** [comment]
Just implemented ```wpi::flush``` and ```wpi::endl``` which do the same as their ```std::``` equivalents. Enjoy!

**Comment by gjurgiel** [comment]
You may also consider adding duplicates of the units.h functionality for std::cout  [here](https://github.com/nholthaus/units/blob/master/include/units.h#L187-L198) and [here](https://github.com/nholthaus/units/blob/master/include/units.h#L2209-L2261). As well as simple functions for frc types like Rotation2d Translation2d or really anything in the geometry folder.

**Comment by theVerySharpFlat** [comment]
> You may also consider adding duplicates of the units.h functionality for std::cout [here](https://github.com/nholthaus/units/blob/master/include/units.h#L187-L198) and [here](https://github.com/nholthaus/units/blob/master/include/units.h#L2209-L2261). As well as simple functions for frc types like Rotation2d Translation2d or really anything in the geometry folder.

Does this mean that I should copy and paste the code for unit to string conversion? Could I do ```using std::to_string; using units::to_string``` and make the compiler guess?

EDIT:
actually, I think the units:: library defines seperate to_string functions in each of its seperate namespaces. This means I have to do a bunch of ```using```s

**Comment by theVerySharpFlat** [comment]
> it would be really nice if we could test this code.

Trying to use wpilib's testing functionallity. Build failed after enabling desktop support and debug testing in build.gradle due to having glibc 2.26 instead of 2.27. The latest glibc version on opensuse leap 15.2 is 2.26 and the latest on 15.3 is 2.31, so I'm upgrading my os. Currently its installing 7536(!) packages. 

I hope you feel my pain.

**Comment by gjurgiel** [comment]
> Does this mean that I should copy and paste the code for unit to string conversion?

Do whatever you think is best. What I linked to is juts what comes when I search for the `<<` operator in the units.h header. I just thought it might be nice not to have to cast everything to a double.

**Comment by theVerySharpFlat** [comment]
I spent most of last night waiting for my computer to unfreeze because my gradle build took up too much ram and I had no swap space. Then, after I force restarted, none of the apps were working so I had to go through and clear cache. Fun.

**Comment by theVerySharpFlat** [comment]
It works. Merge for benefit of the people!

**Pull request merged**
