### PR TITLE
Doxygen implementation

### LINKED ISSUE #48: Doxygen Workflow on PRs
It seems the workflow builds the page even for PRs to main, so I think we have a couple options:
1. We can allow these because it keeps the #47 PR constantly building
2. We can get rid of it and test the build at the very end
3. We can change the workflow to only build on doxygen branch commits

### PR DESCRIPTION
**Pull request by abheekda1**
Use this pull request to add documentation, once everything's finished the merge should hopefully go smoothly. Every once in a while we should make sure to merge main into here. 

To use:
- Commit to `doxygen` branch
- Push

#### TODO:
- [ ] FeedForward
- [x] HolonomicDrive
- [x] HolonomicDriveOdometry
- [x] HolonomicTrajectoryCommand
- [x] MecanumDrive
- [ ] MecanumEncoderOdometry
- [ ] PositionController
- [x] SparkMaxPositionController
- [x] SparkMaxVelocityController
- [ ] TalonFXVelocityController
- [ ] TalonSRXVelocityController
- [ ] VelocityController

- [x] Panskace

For the first commit I've just gone ahead and added an icon.

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
@ADawesomeguy  How do we build the documentation?

**Comment by abheekda1** [comment]
You should just be able to run `doxygen docs/Doxyfile` to generate the HTML in `docs/html` after that if you have python installed you can spin up a simple web server at `http://localhost:8000` by running `python3 -m http.server -d docs/html`.

**Comment by theVerySharpFlat** [comment]
Nice, thanks

**Comment by abheekda1** [comment]
#48

**Comment by abheekda1** [comment]
Closes #17 because this should be the last thing we need to do for that.

**Comment by theVerySharpFlat** [comment]
This movement is dead.

**Comment by abheekda1** [comment]
#79

**Comment by theVerySharpFlat** [comment]
resolved merge conflict in SparkMaxPositionController to make sure that the write documentation comments go with the right functions

**Comment by abheekda1** [comment]
Nice, we be gaming.

**Comment by theVerySharpFlat** [comment]
Documented followers. @ADawesomeguy are the docs being updated with every commit?

**Comment by abheekda1** [comment]
should be

**Comment by theVerySharpFlat** [comment]
ok, yeah there's something wrong with my documentation then

**Comment by abheekda1** [comment]
@theVerySharpFlat is it working now?

**Pull request merged**
